#!/bin/bash
echo "🚀 DEPLOYMENT NUTRI PLAN PLUS"
echo "============================="
echo ""
echo "📖 AM CREAT 2 GHIDURI PENTRU TINE:"
echo ""
echo "1️⃣  DEPLOY_NOW.md - Ghid RAPID (15 minute)"
echo "    - Pași simpli, direct la obiectiv"
echo "    - cat DEPLOY_NOW.md"
echo ""
echo "2️⃣  DEPLOYMENT_GUIDE.md - Ghid COMPLET"
echo "    - Detaliat cu troubleshooting"
echo "    - cat DEPLOYMENT_GUIDE.md"
echo ""
echo "🎯 PRIMUL PAS:"
echo "   Deschide https://github.com/new"
echo "   Creează repo: nutri-plan-plus"
echo ""
echo "📝 AL DOILEA PAS:"
echo "   Rulează:"
echo "   git remote add origin https://github.com/USERNAME/nutri-plan-plus.git"
echo "   git push -u origin main"
echo ""
echo "✅ APOI URMEAZĂ DEPLOY_NOW.md pentru restul!"
echo ""
