// HARDCODED RECIPES - funcționează IMEDIAT fără bază de date!
// Minim 3 opțiuni pentru fiecare meal_type x phase
const recipes = [
  // =============== PHASE 1 ===============
  // BREAKFAST (4 opțiuni)
  { id: 1, name: "Frozen Mango Smoothie", name_ro: "Smoothie cu Mango", phase: 1, meal_type: "breakfast", calories: 280, protein: 25, carbs: 45, fat: 1, ingredients_en: ["2 cups mango", "1 cup almond milk", "protein powder"], ingredients_ro: ["2 căni mango", "1 cană lapte migdale", "proteină"], instructions_en: ["Blend all"], instructions_ro: ["Mixează tot"], image_url: "https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=800", is_vegetarian: true, is_vegan: true },
  { id: 2, name: "Strawberry Rye Toast", name_ro: "Toast din Secară cu Căpșuni", phase: 1, meal_type: "breakfast", calories: 350, protein: 20, carbs: 55, fat: 2, ingredients_en: ["2 slices rye bread", "2 egg whites", "strawberries"], ingredients_ro: ["2 felii pâine de secară", "2 albușuri", "căpșuni"], instructions_en: ["Cook and top"], instructions_ro: ["Gătește și garnisește"], image_url: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800", is_vegetarian: true },
  { id: 3, name: "Oatmeal with Berries", name_ro: "Ovăz cu Fructe de Pădure", phase: 1, meal_type: "breakfast", calories: 320, protein: 15, carbs: 58, fat: 3, ingredients_en: ["1 cup oats", "berries", "water"], ingredients_ro: ["1 cană ovăz", "fructe de pădure", "apă"], instructions_en: ["Cook oats with water", "Top with berries"], instructions_ro: ["Fierbe ovăz pe apă", "Adaugă fructe"], image_url: "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800", is_vegetarian: true },
  { id: 4, name: "Apple Oat Pancakes", name_ro: "Clătite cu Mere și Ovăz", phase: 1, meal_type: "breakfast", calories: 340, protein: 18, carbs: 60, fat: 2, ingredients_en: ["1 apple", "2 eggs", "oats"], ingredients_ro: ["1 măr", "2 ouă", "ovăz"], instructions_en: ["Grate apple and cook"], instructions_ro: ["Rade mărul și gătește"], image_url: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=800", is_vegetarian: true },
  
  // LUNCH (4 opțiuni)
  { id: 5, name: "Tuna Salad with Brown Rice", name_ro: "Salată cu Ton și Orez Brun", phase: 1, meal_type: "lunch", calories: 380, protein: 35, carbs: 40, fat: 5, ingredients_en: ["150g tuna", "1 cup brown rice", "spinach", "cucumber", "tomatoes"], ingredients_ro: ["150g ton", "1 cană orez brun", "spanac", "castravete", "roșii"], instructions_en: ["Cook brown rice", "Mix with tuna and vegetables"], instructions_ro: ["Fierbe orez brun", "Amestecă cu ton și legume"], image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800", is_vegetarian: false },
  { id: 6, name: "Chicken Rye Sandwich", name_ro: "Sandviș Pui pe Secară", phase: 1, meal_type: "lunch", calories: 420, protein: 40, carbs: 48, fat: 4, ingredients_en: ["chicken", "rye bread", "lettuce"], ingredients_ro: ["pui", "pâine de secară", "salată"], instructions_en: ["Grill and assemble"], instructions_ro: ["Gătește și asamblează"], image_url: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800", is_vegetarian: false },
  { id: 7, name: "Turkey Breast", name_ro: "Piept de Curcan", phase: 1, meal_type: "lunch", calories: 400, protein: 42, carbs: 42, fat: 4, ingredients_en: ["180g turkey", "brown rice", "vegetables"], ingredients_ro: ["180g curcan", "orez brun", "legume"], instructions_en: ["Grill turkey"], instructions_ro: ["Gătește curcanul"], image_url: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800", is_vegetarian: false },
  { id: 8, name: "Lentil Soup", name_ro: "Supă de Linte", phase: 1, meal_type: "lunch", calories: 360, protein: 20, carbs: 55, fat: 3, ingredients_en: ["lentils", "vegetables"], ingredients_ro: ["linte", "legume"], instructions_en: ["Boil"], instructions_ro: ["Fierbe"], image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800", is_vegetarian: true, is_vegan: true },
  
  // DINNER (4 opțiuni)
  { id: 9, name: "Turkey Chili", name_ro: "Chili Curcan", phase: 1, meal_type: "dinner", calories: 450, protein: 45, carbs: 50, fat: 6, ingredients_en: ["turkey", "beans", "tomatoes"], ingredients_ro: ["curcan", "fasole", "roșii"], instructions_en: ["Simmer 20min"], instructions_ro: ["Fierbe 20min"], image_url: "https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?w=800", is_vegetarian: false },
  { id: 10, name: "Chicken Stir-Fry", name_ro: "Pui Stir-Fry", phase: 1, meal_type: "dinner", calories: 400, protein: 42, carbs: 45, fat: 5, ingredients_en: ["chicken", "vegetables", "rice"], ingredients_ro: ["pui", "legume", "orez"], instructions_en: ["Stir-fry"], instructions_ro: ["Sotează"], image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800", is_vegetarian: false },
  { id: 11, name: "Beef with Quinoa", name_ro: "Vită cu Quinoa", phase: 1, meal_type: "dinner", calories: 480, protein: 48, carbs: 52, fat: 6, ingredients_en: ["lean beef", "quinoa", "vegetables"], ingredients_ro: ["carne slabă", "quinoa", "legume"], instructions_en: ["Grill and combine"], instructions_ro: ["Gătește și combină"], image_url: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800", is_vegetarian: false },
  { id: 12, name: "White Fish with Rice", name_ro: "Pește Alb cu Orez", phase: 1, meal_type: "dinner", calories: 420, protein: 40, carbs: 50, fat: 4, ingredients_en: ["white fish", "brown rice"], ingredients_ro: ["pește alb", "orez brun"], instructions_en: ["Bake fish"], instructions_ro: ["Coace peștele"], image_url: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800", is_vegetarian: false },
  
  // SNACK1 (3 opțiuni)
  { id: 13, name: "Apple", name_ro: "Măr", phase: 1, meal_type: "snack1", calories: 95, protein: 0, carbs: 25, fat: 0, ingredients_en: ["1 apple"], ingredients_ro: ["1 măr"], instructions_en: ["Eat fresh"], instructions_ro: ["Mănâncă proaspăt"], image_url: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=800", is_vegetarian: true, is_vegan: true },
  { id: 14, name: "Peach", name_ro: "Piersică", phase: 1, meal_type: "snack1", calories: 60, protein: 1, carbs: 15, fat: 0, ingredients_en: ["1 peach"], ingredients_ro: ["1 piersică"], instructions_en: ["Wash and eat"], instructions_ro: ["Spală și mănâncă"], image_url: "https://images.unsplash.com/photo-1629828874514-944dd0d9c48b?w=800", is_vegetarian: true, is_vegan: true },
  { id: 15, name: "Pear", name_ro: "Pară", phase: 1, meal_type: "snack1", calories: 100, protein: 1, carbs: 27, fat: 0, ingredients_en: ["1 pear"], ingredients_ro: ["1 pară"], instructions_en: ["Wash and eat"], instructions_ro: ["Spală și mănâncă"], image_url: "https://images.unsplash.com/photo-1585059895524-72359e9ab3f0?w=800", is_vegetarian: true, is_vegan: true },
  
  // SNACK2 (4 opțiuni)
  { id: 16, name: "Orange", name_ro: "Portocală", phase: 1, meal_type: "snack2", calories: 62, protein: 1, carbs: 15, fat: 0, ingredients_en: ["1 orange"], ingredients_ro: ["1 portocală"], instructions_en: ["Peel and eat"], instructions_ro: ["Curăță și mănâncă"], image_url: "https://images.unsplash.com/photo-1547514701-42782101795e?w=800", is_vegetarian: true, is_vegan: true },
  { id: 17, name: "Berries", name_ro: "Fructe de pădure", phase: 1, meal_type: "snack2", calories: 80, protein: 1, carbs: 18, fat: 0, ingredients_en: ["1 cup berries"], ingredients_ro: ["1 cană fructe"], instructions_en: ["Wash and eat"], instructions_ro: ["Spală și mănâncă"], image_url: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=800", is_vegetarian: true, is_vegan: true },
  { id: 18, name: "Kiwi", name_ro: "Kiwi", phase: 1, meal_type: "snack2", calories: 90, protein: 2, carbs: 22, fat: 0, ingredients_en: ["2 kiwis"], ingredients_ro: ["2 kiwi"], instructions_en: ["Peel and eat"], instructions_ro: ["Curăță și mănâncă"], image_url: "https://images.unsplash.com/photo-1585059895524-72359e9ab3f0?w=800", is_vegetarian: true, is_vegan: true },
  { id: 19, name: "Watermelon", name_ro: "Pepene Verde", phase: 1, meal_type: "snack2", calories: 92, protein: 2, carbs: 23, fat: 0, ingredients_en: ["2 cups watermelon"], ingredients_ro: ["2 căni pepene"], instructions_en: ["Cut and serve"], instructions_ro: ["Taie și servește"], image_url: "https://images.unsplash.com/photo-1587049352846-4a222e784210?w=800", is_vegetarian: true, is_vegan: true },
  
  // =============== PHASE 2 ===============
  // BREAKFAST (3 opțiuni)
  { id: 20, name: "Egg White Scramble", name_ro: "Omletă din Albuș", phase: 2, meal_type: "breakfast", calories: 180, protein: 25, carbs: 10, fat: 3, ingredients_en: ["4 egg whites", "vegetables"], ingredients_ro: ["4 albușuri", "legume"], instructions_en: ["Cook"], instructions_ro: ["Gătește"], image_url: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800", is_vegetarian: true },
  { id: 21, name: "Turkey Egg White Wrap", name_ro: "Wrap cu Curcan și Albuș", phase: 2, meal_type: "breakfast", calories: 200, protein: 28, carbs: 8, fat: 5, ingredients_en: ["turkey slices", "egg whites", "lettuce"], ingredients_ro: ["felii curcan", "albușuri", "salată"], instructions_en: ["Wrap and eat"], instructions_ro: ["Înfășoară și mănâncă"], image_url: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800", is_vegetarian: false },
  { id: 22, name: "Chicken & Spinach", name_ro: "Pui cu Spanac", phase: 2, meal_type: "breakfast", calories: 190, protein: 30, carbs: 6, fat: 4, ingredients_en: ["chicken breast", "spinach"], ingredients_ro: ["piept pui", "spanac"], instructions_en: ["Cook"], instructions_ro: ["Gătește"], image_url: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800", is_vegetarian: false },
  
  // LUNCH (3 opțiuni)
  { id: 23, name: "Grilled Chicken", name_ro: "Pui la Grătar", phase: 2, meal_type: "lunch", calories: 320, protein: 45, carbs: 8, fat: 12, ingredients_en: ["chicken", "asparagus"], ingredients_ro: ["pui", "sparanghel"], instructions_en: ["Grill"], instructions_ro: ["La grătar"], image_url: "https://images.unsplash.com/photo-1612057888294-9c11a7178022?w=800", is_vegetarian: false },
  { id: 24, name: "Grilled Fish Salad", name_ro: "Salată cu Pește", phase: 2, meal_type: "lunch", calories: 300, protein: 42, carbs: 6, fat: 12, ingredients_en: ["white fish", "leafy greens"], ingredients_ro: ["pește alb", "salată verde"], instructions_en: ["Grill fish"], instructions_ro: ["Gătește peștele"], image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800", is_vegetarian: false },
  { id: 25, name: "Turkey & Broccoli", name_ro: "Curcan cu Broccoli", phase: 2, meal_type: "lunch", calories: 310, protein: 44, carbs: 10, fat: 10, ingredients_en: ["turkey", "broccoli"], ingredients_ro: ["curcan", "broccoli"], instructions_en: ["Steam and serve"], instructions_ro: ["Gătește la abur"], image_url: "https://images.unsplash.com/photo-1628773822503-930a7eaecf80?w=800", is_vegetarian: false },
  
  // DINNER (3 opțiuni)
  { id: 26, name: "Grilled Fish", name_ro: "Pește la Grătar", phase: 2, meal_type: "dinner", calories: 340, protein: 50, carbs: 5, fat: 14, ingredients_en: ["white fish", "lemon"], ingredients_ro: ["pește alb", "lămâie"], instructions_en: ["Season and grill"], instructions_ro: ["Condimentează și gătește"], image_url: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800", is_vegetarian: false },
  { id: 27, name: "Turkey Lettuce Wraps", name_ro: "Wraps cu Curcan", phase: 2, meal_type: "dinner", calories: 310, protein: 44, carbs: 8, fat: 12, ingredients_en: ["ground turkey", "lettuce"], ingredients_ro: ["curcan tocat", "salată"], instructions_en: ["Cook and wrap"], instructions_ro: ["Gătește și înfășoară"], image_url: "https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?w=800", is_vegetarian: false },
  { id: 28, name: "Chicken Breast", name_ro: "Piept de Pui", phase: 2, meal_type: "dinner", calories: 300, protein: 48, carbs: 4, fat: 10, ingredients_en: ["chicken breast", "green beans"], ingredients_ro: ["piept pui", "fasole verde"], instructions_en: ["Bake"], instructions_ro: ["Coace"], image_url: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800", is_vegetarian: false },
  
  // SNACK1 (3 opțiuni)
  { id: 29, name: "Celery Hummus", name_ro: "Țelină cu Hummus", phase: 2, meal_type: "snack1", calories: 120, protein: 4, carbs: 12, fat: 6, ingredients_en: ["celery", "hummus"], ingredients_ro: ["țelină", "hummus"], instructions_en: ["Dip"], instructions_ro: ["Înmoaie"], image_url: "https://images.unsplash.com/photo-1529288475508-c303ace43d0f?w=800", is_vegetarian: true },
  { id: 30, name: "Turkey Roll-Ups", name_ro: "Rulouri de Curcan", phase: 2, meal_type: "snack1", calories: 100, protein: 20, carbs: 2, fat: 2, ingredients_en: ["turkey slices"], ingredients_ro: ["felii curcan"], instructions_en: ["Roll and eat"], instructions_ro: ["Rulează și mănâncă"], image_url: "https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=800", is_vegetarian: false },
  { id: 31, name: "Cherry Tomatoes", name_ro: "Roșii Cherry", phase: 2, meal_type: "snack1", calories: 40, protein: 2, carbs: 8, fat: 0, ingredients_en: ["1 cup cherry tomatoes"], ingredients_ro: ["1 cană roșii cherry"], instructions_en: ["Wash and eat"], instructions_ro: ["Spală și mănâncă"], image_url: "https://images.unsplash.com/photo-1592838064575-70ed626d3a0e?w=800", is_vegetarian: true, is_vegan: true },
  
  // SNACK2 (3 opțiuni)
  { id: 32, name: "Turkey Slices", name_ro: "Felii de Curcan", phase: 2, meal_type: "snack2", calories: 110, protein: 22, carbs: 2, fat: 2, ingredients_en: ["turkey slices"], ingredients_ro: ["felii curcan"], instructions_en: ["Serve cold"], instructions_ro: ["Servește rece"], image_url: "https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=800", is_vegetarian: false },
  { id: 33, name: "Cucumber", name_ro: "Castravete", phase: 2, meal_type: "snack2", calories: 45, protein: 2, carbs: 10, fat: 0, ingredients_en: ["1 cucumber"], ingredients_ro: ["1 castravete"], instructions_en: ["Slice"], instructions_ro: ["Taie"], image_url: "https://images.unsplash.com/photo-1604977042946-1eecc30f269e?w=800", is_vegetarian: true, is_vegan: true },
  { id: 34, name: "Bell Pepper Strips", name_ro: "Felii Ardei Gras", phase: 2, meal_type: "snack2", calories: 50, protein: 2, carbs: 12, fat: 0, ingredients_en: ["1 bell pepper"], ingredients_ro: ["1 ardei gras"], instructions_en: ["Slice"], instructions_ro: ["Taie"], image_url: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=800", is_vegetarian: true, is_vegan: true },
  
  // =============== PHASE 3 ===============
  // BREAKFAST (3 opțiuni)
  { id: 35, name: "Avocado Toast with Eggs", name_ro: "Toast cu Avocado și Ouă", phase: 3, meal_type: "breakfast", calories: 420, protein: 20, carbs: 35, fat: 24, ingredients_en: ["rye bread", "avocado", "eggs"], ingredients_ro: ["pâine de secară", "avocado", "ouă"], instructions_en: ["Toast rye bread and top"], instructions_ro: ["Prăjește pâinea de secară și garnisește"], image_url: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800", is_vegetarian: true },
  { id: 36, name: "Nut Butter Rye Toast", name_ro: "Toast de Secară cu Unt de Arahide", phase: 3, meal_type: "breakfast", calories: 380, protein: 18, carbs: 38, fat: 20, ingredients_en: ["rye bread", "almond butter", "berries"], ingredients_ro: ["pâine de secară", "unt migdale", "fructe"], instructions_en: ["Toast rye bread, spread and top"], instructions_ro: ["Prăjește pâinea de secară, întinde și garnisește"], image_url: "https://images.unsplash.com/photo-1525351326368-efbb5cb6814d?w=800", is_vegetarian: true },
  { id: 37, name: "Veggie Omelette with Avocado", name_ro: "Omletă cu Legume și Avocado", phase: 3, meal_type: "breakfast", calories: 350, protein: 22, carbs: 25, fat: 18, ingredients_en: ["3 eggs", "vegetables", "avocado"], ingredients_ro: ["3 ouă", "legume", "avocado"], instructions_en: ["Cook omelette with veggies"], instructions_ro: ["Gătește omleta cu legume"], image_url: "https://images.unsplash.com/photo-1546069901-eacef0df6022?w=800", is_vegetarian: true },
  
  // LUNCH (3 opțiuni)
  { id: 38, name: "Salmon with Vegetables", name_ro: "Somon cu Legume", phase: 3, meal_type: "lunch", calories: 480, protein: 40, carbs: 25, fat: 25, ingredients_en: ["salmon", "vegetables"], ingredients_ro: ["somon", "legume"], instructions_en: ["Bake"], instructions_ro: ["Coace"], image_url: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800", is_vegetarian: false },
  { id: 39, name: "Chicken Avocado Salad", name_ro: "Salată Pui cu Avocado", phase: 3, meal_type: "lunch", calories: 450, protein: 38, carbs: 28, fat: 22, ingredients_en: ["chicken", "avocado", "greens"], ingredients_ro: ["pui", "avocado", "salată"], instructions_en: ["Mix all"], instructions_ro: ["Amestecă"], image_url: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800", is_vegetarian: false },
  { id: 40, name: "Tuna Avocado Bowl", name_ro: "Bowl cu Ton și Avocado", phase: 3, meal_type: "lunch", calories: 460, protein: 35, carbs: 30, fat: 24, ingredients_en: ["tuna", "avocado", "quinoa"], ingredients_ro: ["ton", "avocado", "quinoa"], instructions_en: ["Mix"], instructions_ro: ["Amestecă"], image_url: "https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=800", is_vegetarian: false },
  
  // DINNER (4 opțiuni)
  { id: 41, name: "Steak with Sweet Potato", name_ro: "Friptură cu Cartof Dulce", phase: 3, meal_type: "dinner", calories: 550, protein: 48, carbs: 42, fat: 22, ingredients_en: ["steak", "sweet potato"], ingredients_ro: ["friptură", "cartof dulce"], instructions_en: ["Grill and roast"], instructions_ro: ["Gătește"], image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800", is_vegetarian: false },
  { id: 42, name: "Salmon Bowl", name_ro: "Bowl cu Somon", phase: 3, meal_type: "dinner", calories: 520, protein: 45, carbs: 38, fat: 24, ingredients_en: ["salmon", "quinoa", "avocado"], ingredients_ro: ["somon", "quinoa", "avocado"], instructions_en: ["Bake and assemble"], instructions_ro: ["Coace și asamblează"], image_url: "https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?w=800", is_vegetarian: false },
  { id: 43, name: "Chicken Thighs", name_ro: "Pulpe de Pui", phase: 3, meal_type: "dinner", calories: 480, protein: 42, carbs: 28, fat: 24, ingredients_en: ["chicken thighs", "vegetables"], ingredients_ro: ["pulpe pui", "legume"], instructions_en: ["Bake"], instructions_ro: ["Coace"], image_url: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800", is_vegetarian: false },
  { id: 44, name: "Pork Chop with Veggies", name_ro: "Cotlet de Porc cu Legume", phase: 3, meal_type: "dinner", calories: 500, protein: 44, carbs: 32, fat: 26, ingredients_en: ["pork chop", "vegetables", "olive oil"], ingredients_ro: ["cotlet porc", "legume", "ulei măsline"], instructions_en: ["Grill and serve"], instructions_ro: ["Gătește și servește"], image_url: "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=800", is_vegetarian: false },
  
  // SNACK1 (3 opțiuni)
  { id: 45, name: "Mixed Nuts", name_ro: "Mix de Nuci", phase: 3, meal_type: "snack1", calories: 200, protein: 6, carbs: 8, fat: 18, ingredients_en: ["almonds", "walnuts", "cashews"], ingredients_ro: ["migdale", "nuci", "caju"], instructions_en: ["Portion"], instructions_ro: ["Porționează"], image_url: "https://images.unsplash.com/photo-1569288063643-5d29ad64df09?w=800", is_vegetarian: true },
  { id: 46, name: "Hummus with Veggies", name_ro: "Hummus cu Legume", phase: 3, meal_type: "snack1", calories: 180, protein: 6, carbs: 18, fat: 10, ingredients_en: ["hummus", "carrots", "celery"], ingredients_ro: ["hummus", "morcovi", "țelină"], instructions_en: ["Dip"], instructions_ro: ["Înmoaie"], image_url: "https://images.unsplash.com/photo-1529288475508-c303ace43d0f?w=800", is_vegetarian: true, is_vegan: true },
  { id: 47, name: "Apple with Nut Butter", name_ro: "Măr cu Unt de Migdale", phase: 3, meal_type: "snack1", calories: 220, protein: 5, carbs: 28, fat: 12, ingredients_en: ["1 apple", "almond butter"], ingredients_ro: ["1 măr", "unt migdale"], instructions_en: ["Slice and spread"], instructions_ro: ["Taie și întinde"], image_url: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=800", is_vegetarian: true },
  
  // SNACK2 (3 opțiuni)
  { id: 48, name: "Walnuts", name_ro: "Nuci", phase: 3, meal_type: "snack2", calories: 185, protein: 4, carbs: 4, fat: 18, ingredients_en: ["10 walnuts"], ingredients_ro: ["10 nuci"], instructions_en: ["Portion"], instructions_ro: ["Porționează"], image_url: "https://images.unsplash.com/photo-1622484211043-e6d2f7d5a5eb?w=800", is_vegetarian: true, is_vegan: true },
  { id: 49, name: "Cashews", name_ro: "Caju", phase: 3, meal_type: "snack2", calories: 160, protein: 5, carbs: 9, fat: 13, ingredients_en: ["15 cashews"], ingredients_ro: ["15 caju"], instructions_en: ["Portion"], instructions_ro: ["Porționează"], image_url: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800", is_vegetarian: true, is_vegan: true },
  { id: 50, name: "Avocado Slices", name_ro: "Felii de Avocado", phase: 3, meal_type: "snack2", calories: 160, protein: 2, carbs: 9, fat: 15, ingredients_en: ["1/2 avocado"], ingredients_ro: ["1/2 avocado"], instructions_en: ["Slice"], instructions_ro: ["Taie"], image_url: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=800", is_vegetarian: true, is_vegan: true },
  
  // =============== PHASE 1 - REȚETE NOI ORIGINALE ===============
  // BREAKFAST (10 rețete noi)
  { id: 51, name: "Quinoa Porridge with Berries", name_ro: "Terci de Quinoa cu Fructe de Pădure", phase: 1, meal_type: "breakfast", calories: 310, protein: 18, carbs: 52, fat: 3, ingredients_en: ["1 cup quinoa", "1 cup berries", "water", "cinnamon"], ingredients_ro: ["1 cană quinoa", "1 cană fructe de pădure", "apă", "scorțișoară"], instructions_en: ["Cook quinoa in water", "Top with fresh berries", "Sprinkle cinnamon"], instructions_ro: ["Fierbe quinoa în apă", "Adaugă fructe proaspete", "Presară scorțișoară"], image_url: "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800", is_vegetarian: true, is_vegan: true },
  { id: 52, name: "Rice Cakes with Mango", name_ro: "Turtițe de Orez cu Mango", phase: 1, meal_type: "breakfast", calories: 280, protein: 12, carbs: 58, fat: 2, ingredients_en: ["3 rice cakes", "1 cup mango chunks", "protein powder"], ingredients_ro: ["3 turtițe orez", "1 cană bucăți mango", "proteină pudră"], instructions_en: ["Top rice cakes with mango", "Add protein powder"], instructions_ro: ["Pune mango pe turtițe", "Adaugă proteină"], image_url: "https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=800", is_vegetarian: true },
  { id: 53, name: "Brown Rice Breakfast Bowl", name_ro: "Bowl de Orez Brun la Mic Dejun", phase: 1, meal_type: "breakfast", calories: 340, protein: 20, carbs: 60, fat: 2, ingredients_en: ["1 cup brown rice", "2 egg whites", "strawberries", "blueberries"], ingredients_ro: ["1 cană orez brun", "2 albușuri", "căpșuni", "afine"], instructions_en: ["Cook rice and egg whites", "Top with fresh berries"], instructions_ro: ["Fierbe orez și albușuri", "Adaugă fructe proaspete"], image_url: "https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?w=800", is_vegetarian: true },
  { id: 54, name: "Millet Porridge with Peaches", name_ro: "Terci de Mei cu Piersici", phase: 1, meal_type: "breakfast", calories: 320, protein: 16, carbs: 62, fat: 3, ingredients_en: ["1 cup millet", "2 peaches", "water"], ingredients_ro: ["1 cană mei", "2 piersici", "apă"], instructions_en: ["Cook millet until soft", "Slice peaches on top"], instructions_ro: ["Fierbe mei până e moale", "Taie piersici deasupra"], image_url: "https://images.unsplash.com/photo-1629828874514-944dd0d9c48b?w=800", is_vegetarian: true, is_vegan: true },
  { id: 55, name: "Buckwheat Pancakes with Berries", name_ro: "Clătite de Hrișcă cu Fructe", phase: 1, meal_type: "breakfast", calories: 350, protein: 22, carbs: 58, fat: 2, ingredients_en: ["buckwheat flour", "3 egg whites", "1 cup mixed berries"], ingredients_ro: ["făină hrișcă", "3 albușuri", "1 cană fructe mixte"], instructions_en: ["Mix flour with egg whites", "Cook as pancakes", "Top with berries"], instructions_ro: ["Amestecă făină cu albușuri", "Gătește ca clătite", "Adaugă fructe"], image_url: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=800", is_vegetarian: true },
  { id: 56, name: "Rye Bread French Toast", name_ro: "Pâine Pierdută din Secară", phase: 1, meal_type: "breakfast", calories: 360, protein: 24, carbs: 54, fat: 3, ingredients_en: ["2 slices rye bread", "3 egg whites", "strawberries", "cinnamon"], ingredients_ro: ["2 felii pâine secară", "3 albușuri", "căpșuni", "scorțișoară"], instructions_en: ["Dip bread in egg whites", "Cook until golden", "Top with strawberries"], instructions_ro: ["Înmoaie pâinea în albușuri", "Gătește până devine aurie", "Adaugă căpșuni"], image_url: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800", is_vegetarian: true },
  { id: 57, name: "Barley Breakfast Bowl", name_ro: "Bowl de Orz la Mic Dejun", phase: 1, meal_type: "breakfast", calories: 330, protein: 19, carbs: 60, fat: 2, ingredients_en: ["1 cup barley", "1 apple", "cinnamon"], ingredients_ro: ["1 cană orz", "1 măr", "scorțișoară"], instructions_en: ["Cook barley in water", "Dice apple", "Mix and sprinkle cinnamon"], instructions_ro: ["Fierbe orz în apă", "Taie măr cubulețe", "Amestecă și presară scorțișoară"], image_url: "https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?w=800", is_vegetarian: true, is_vegan: true },
  { id: 58, name: "Spelt Porridge with Pear", name_ro: "Terci de Alac cu Pară", phase: 1, meal_type: "breakfast", calories: 340, protein: 18, carbs: 64, fat: 2, ingredients_en: ["1 cup spelt flakes", "1 pear", "water"], ingredients_ro: ["1 cană fulgi alac", "1 pară", "apă"], instructions_en: ["Cook spelt until creamy", "Slice pear on top"], instructions_ro: ["Fierbe alac până e cremos", "Taie pară deasupra"], image_url: "https://images.unsplash.com/photo-1585059895524-72359e9ab3f0?w=800", is_vegetarian: true, is_vegan: true },
  { id: 59, name: "Wild Rice with Orange", name_ro: "Orez Sălbatic cu Portocală", phase: 1, meal_type: "breakfast", calories: 300, protein: 17, carbs: 56, fat: 2, ingredients_en: ["1 cup wild rice", "1 orange", "protein powder"], ingredients_ro: ["1 cană orez sălbatic", "1 portocală", "proteină pudră"], instructions_en: ["Cook wild rice", "Peel and segment orange", "Mix together"], instructions_ro: ["Fierbe orez sălbatic", "Curăță și taie portocala", "Amestecă"], image_url: "https://images.unsplash.com/photo-1547514701-42782101795e?w=800", is_vegetarian: true },
  { id: 60, name: "Kamut Flakes with Kiwi", name_ro: "Fulgi Kamut cu Kiwi", phase: 1, meal_type: "breakfast", calories: 315, protein: 20, carbs: 58, fat: 2, ingredients_en: ["1 cup kamut flakes", "2 kiwis", "water"], ingredients_ro: ["1 cană fulgi kamut", "2 kiwi", "apă"], instructions_en: ["Cook kamut flakes", "Peel and slice kiwis", "Combine"], instructions_ro: ["Fierbe fulgi kamut", "Curăță și taie kiwi", "Combină"], image_url: "https://images.unsplash.com/photo-1585059895524-72359e9ab3f0?w=800", is_vegetarian: true },

  // LUNCH (10 rețete noi)
  { id: 61, name: "Chicken with Bulgur Pilaf", name_ro: "Pui cu Bulgur Pilaf", phase: 1, meal_type: "lunch", calories: 410, protein: 38, carbs: 48, fat: 5, ingredients_en: ["180g chicken breast", "1 cup bulgur", "onion", "tomatoes"], ingredients_ro: ["180g piept pui", "1 cană bulgur", "ceapă", "roșii"], instructions_en: ["Cook bulgur with vegetables", "Grill chicken", "Combine"], instructions_ro: ["Gătește bulgur cu legume", "Pregătește pui la grătar", "Combină"], image_url: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800", is_vegetarian: false },
  { id: 62, name: "Turkey Quinoa Salad", name_ro: "Salată de Curcan cu Quinoa", phase: 1, meal_type: "lunch", calories: 395, protein: 40, carbs: 44, fat: 4, ingredients_en: ["180g turkey breast", "1 cup quinoa", "cucumber", "bell pepper"], ingredients_ro: ["180g piept curcan", "1 cană quinoa", "castravete", "ardei gras"], instructions_en: ["Cook quinoa", "Dice vegetables", "Grill turkey and mix"], instructions_ro: ["Fierbe quinoa", "Taie legume cubulețe", "Gătește curcan și amestecă"], image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800", is_vegetarian: false },
  { id: 63, name: "White Fish with Barley", name_ro: "Pește Alb cu Orz", phase: 1, meal_type: "lunch", calories: 380, protein: 36, carbs: 46, fat: 4, ingredients_en: ["180g white fish", "1 cup barley", "lemon", "parsley"], ingredients_ro: ["180g pește alb", "1 cană orz", "lămâie", "pătrunjel"], instructions_en: ["Cook barley", "Bake fish with lemon", "Serve together"], instructions_ro: ["Fierbe orz", "Coace pește cu lămâie", "Servește împreună"], image_url: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800", is_vegetarian: false },
  { id: 64, name: "Chickpea Brown Rice Bowl", name_ro: "Bowl de Năut cu Orez Brun", phase: 1, meal_type: "lunch", calories: 370, protein: 22, carbs: 62, fat: 3, ingredients_en: ["1 cup chickpeas", "1 cup brown rice", "spinach", "tomatoes"], ingredients_ro: ["1 cană năut", "1 cană orez brun", "spanac", "roșii"], instructions_en: ["Cook rice and chickpeas", "Add vegetables", "Season"], instructions_ro: ["Fierbe orez și năut", "Adaugă legume", "Condimentează"], image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800", is_vegetarian: true, is_vegan: true },
  { id: 65, name: "Turkey Millet Stir-Fry", name_ro: "Curcan cu Mei Sotate", phase: 1, meal_type: "lunch", calories: 405, protein: 42, carbs: 45, fat: 5, ingredients_en: ["180g turkey", "1 cup millet", "broccoli", "carrots"], ingredients_ro: ["180g curcan", "1 cană mei", "broccoli", "morcovi"], instructions_en: ["Cook millet", "Stir-fry turkey with vegetables"], instructions_ro: ["Fierbe mei", "Sotează curcan cu legume"], image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800", is_vegetarian: false },
  { id: 66, name: "Chicken Wild Rice Soup", name_ro: "Supă de Pui cu Orez Sălbatic", phase: 1, meal_type: "lunch", calories: 385, protein: 38, carbs: 48, fat: 4, ingredients_en: ["180g chicken", "1 cup wild rice", "celery", "carrots", "onion"], ingredients_ro: ["180g pui", "1 cană orez sălbatic", "țelină", "morcovi", "ceapă"], instructions_en: ["Boil all ingredients", "Season with herbs"], instructions_ro: ["Fierbe toate ingredientele", "Condimentează cu ierburi"], image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800", is_vegetarian: false },
  { id: 67, name: "Black Bean Quinoa Wrap", name_ro: "Wrap cu Fasole Neagră și Quinoa", phase: 1, meal_type: "lunch", calories: 390, protein: 24, carbs: 68, fat: 3, ingredients_en: ["1 cup black beans", "1 cup quinoa", "lettuce", "tomatoes", "rye wrap"], ingredients_ro: ["1 cană fasole neagră", "1 cană quinoa", "salată", "roșii", "wrap secară"], instructions_en: ["Cook beans and quinoa", "Fill wrap with vegetables"], instructions_ro: ["Fierbe fasole și quinoa", "Umple wrap cu legume"], image_url: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800", is_vegetarian: true, is_vegan: true },
  { id: 68, name: "Turkey Spelt Salad", name_ro: "Salată de Curcan cu Alac", phase: 1, meal_type: "lunch", calories: 400, protein: 40, carbs: 46, fat: 5, ingredients_en: ["180g turkey", "1 cup spelt berries", "arugula", "cherry tomatoes"], ingredients_ro: ["180g curcan", "1 cană boabe alac", "rucola", "roșii cherry"], instructions_en: ["Cook spelt berries", "Grill turkey", "Toss with greens"], instructions_ro: ["Fierbe boabe alac", "Gătește curcan", "Amestecă cu salată"], image_url: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800", is_vegetarian: false },
  { id: 69, name: "White Fish Kamut Bowl", name_ro: "Bowl de Pește cu Kamut", phase: 1, meal_type: "lunch", calories: 375, protein: 35, carbs: 50, fat: 4, ingredients_en: ["180g white fish", "1 cup kamut", "zucchini", "bell pepper"], ingredients_ro: ["180g pește alb", "1 cană kamut", "dovlecel", "ardei gras"], instructions_en: ["Cook kamut", "Bake fish", "Sauté vegetables", "Combine"], instructions_ro: ["Fierbe kamut", "Coace pește", "Sotează legume", "Combină"], image_url: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800", is_vegetarian: false },
  { id: 70, name: "Lentil Buckwheat Stew", name_ro: "Tocană de Linte cu Hrișcă", phase: 1, meal_type: "lunch", calories: 365, protein: 24, carbs: 62, fat: 3, ingredients_en: ["1 cup lentils", "1 cup buckwheat", "onion", "carrots", "celery"], ingredients_ro: ["1 cană linte", "1 cană hrișcă", "ceapă", "morcovi", "țelină"], instructions_en: ["Boil lentils with vegetables", "Add cooked buckwheat", "Simmer"], instructions_ro: ["Fierbe linte cu legume", "Adaugă hrișcă fiartă", "Las la fiert"], image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800", is_vegetarian: true, is_vegan: true },

  // DINNER (10 rețete noi)
  { id: 71, name: "Turkey Bulgur Chili", name_ro: "Chili de Curcan cu Bulgur", phase: 1, meal_type: "dinner", calories: 445, protein: 44, carbs: 52, fat: 6, ingredients_en: ["200g turkey", "1 cup bulgur", "kidney beans", "tomatoes", "bell pepper"], ingredients_ro: ["200g curcan", "1 cană bulgur", "fasole roșie", "roșii", "ardei gras"], instructions_en: ["Cook turkey and vegetables", "Add bulgur", "Simmer 25 min"], instructions_ro: ["Gătește curcan și legume", "Adaugă bulgur", "Las la fiert 25 min"], image_url: "https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?w=800", is_vegetarian: false },
  { id: 72, name: "Chicken Quinoa Casserole", name_ro: "Caserola de Pui cu Quinoa", phase: 1, meal_type: "dinner", calories: 425, protein: 42, carbs: 50, fat: 5, ingredients_en: ["200g chicken", "1 cup quinoa", "broccoli", "tomatoes"], ingredients_ro: ["200g pui", "1 cană quinoa", "broccoli", "roșii"], instructions_en: ["Layer in baking dish", "Bake 30 minutes"], instructions_ro: ["Așează în tavă", "Coace 30 minute"], image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800", is_vegetarian: false },
  { id: 73, name: "White Fish Brown Rice Bowl", name_ro: "Bowl de Pește cu Orez Brun", phase: 1, meal_type: "dinner", calories: 410, protein: 38, carbs: 54, fat: 4, ingredients_en: ["200g white fish", "1 cup brown rice", "bok choy", "ginger"], ingredients_ro: ["200g pește alb", "1 cană orez brun", "bok choy", "ghimbir"], instructions_en: ["Steam fish", "Cook rice", "Stir-fry vegetables"], instructions_ro: ["Gătește peștele la abur", "Fierbe orez", "Sotează legume"], image_url: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800", is_vegetarian: false },
  { id: 74, name: "Turkey Meatballs with Millet", name_ro: "Chiftele de Curcan cu Mei", phase: 1, meal_type: "dinner", calories: 430, protein: 45, carbs: 48, fat: 6, ingredients_en: ["200g ground turkey", "1 cup millet", "onion", "parsley"], ingredients_ro: ["200g curcan tocat", "1 cană mei", "ceapă", "pătrunjel"], instructions_en: ["Form meatballs", "Bake", "Serve with cooked millet"], instructions_ro: ["Formează chiftele", "Coace", "Servește cu mei fiert"], image_url: "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800", is_vegetarian: false },
  { id: 75, name: "Chicken Wild Rice Bake", name_ro: "Pui cu Orez Sălbatic la Cuptor", phase: 1, meal_type: "dinner", calories: 440, protein: 46, carbs: 50, fat: 5, ingredients_en: ["200g chicken", "1 cup wild rice", "mushrooms", "onion"], ingredients_ro: ["200g pui", "1 cană orez sălbatic", "ciuperci", "ceapă"], instructions_en: ["Mix all ingredients", "Bake 35 minutes"], instructions_ro: ["Amestecă toate ingredientele", "Coace 35 minute"], image_url: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800", is_vegetarian: false },
  { id: 76, name: "Bean Barley Stew", name_ro: "Tocană de Fasole cu Orz", phase: 1, meal_type: "dinner", calories: 385, protein: 26, carbs: 68, fat: 3, ingredients_en: ["1 cup white beans", "1 cup barley", "carrots", "celery", "tomatoes"], ingredients_ro: ["1 cană fasole albă", "1 cană orz", "morcovi", "țelină", "roșii"], instructions_en: ["Boil beans and barley", "Add vegetables", "Simmer 30 min"], instructions_ro: ["Fierbe fasole și orz", "Adaugă legume", "Las la fiert 30 min"], image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800", is_vegetarian: true, is_vegan: true },
  { id: 77, name: "Turkey Spelt Soup", name_ro: "Supă de Curcan cu Alac", phase: 1, meal_type: "dinner", calories: 415, protein: 42, carbs: 52, fat: 5, ingredients_en: ["200g turkey", "1 cup spelt berries", "carrots", "celery", "parsley"], ingredients_ro: ["200g curcan", "1 cană boabe alac", "morcovi", "țelină", "pătrunjel"], instructions_en: ["Boil turkey with vegetables", "Add cooked spelt", "Season"], instructions_ro: ["Fierbe curcan cu legume", "Adaugă alac fiert", "Condimentează"], image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800", is_vegetarian: false },
  { id: 78, name: "Chicken Buckwheat Pilaf", name_ro: "Pilaf de Pui cu Hrișcă", phase: 1, meal_type: "dinner", calories: 420, protein: 44, carbs: 50, fat: 5, ingredients_en: ["200g chicken", "1 cup buckwheat", "onion", "bell pepper"], ingredients_ro: ["200g pui", "1 cană hrișcă", "ceapă", "ardei gras"], instructions_en: ["Cook buckwheat", "Add grilled chicken", "Mix"], instructions_ro: ["Fierbe hrișcă", "Adaugă pui la grătar", "Amestecă"], image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800", is_vegetarian: false },
  { id: 79, name: "White Fish Kamut Stir-Fry", name_ro: "Pește cu Kamut Sotat", phase: 1, meal_type: "dinner", calories: 395, protein: 40, carbs: 48, fat: 4, ingredients_en: ["200g white fish", "1 cup kamut", "snap peas", "carrots"], ingredients_ro: ["200g pește alb", "1 cană kamut", "mazăre", "morcovi"], instructions_en: ["Cook kamut", "Stir-fry fish with vegetables"], instructions_ro: ["Fierbe kamut", "Sotează pește cu legume"], image_url: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800", is_vegetarian: false },
  { id: 80, name: "Lentil Quinoa Curry", name_ro: "Curry de Linte cu Quinoa", phase: 1, meal_type: "dinner", calories: 380, protein: 25, carbs: 64, fat: 4, ingredients_en: ["1 cup lentils", "1 cup quinoa", "curry powder", "coconut milk", "vegetables"], ingredients_ro: ["1 cană linte", "1 cană quinoa", "curry", "lapte cocos", "legume"], instructions_en: ["Cook lentils with curry", "Add quinoa", "Simmer"], instructions_ro: ["Fierbe linte cu curry", "Adaugă quinoa", "Las la fiert"], image_url: "https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?w=800", is_vegetarian: true, is_vegan: true },

  // SNACK1 & SNACK2 (10 rețete noi combined)
  { id: 81, name: "Mango Slices", name_ro: "Felii de Mango", phase: 1, meal_type: "snack1", calories: 100, protein: 1, carbs: 25, fat: 0, ingredients_en: ["1 cup mango"], ingredients_ro: ["1 cană mango"], instructions_en: ["Peel and slice"], instructions_ro: ["Curăță și taie"], image_url: "https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=800", is_vegetarian: true, is_vegan: true },
  { id: 82, name: "Papaya", name_ro: "Papaya", phase: 1, meal_type: "snack1", calories: 119, protein: 1, carbs: 30, fat: 0, ingredients_en: ["1 cup papaya"], ingredients_ro: ["1 cană papaya"], instructions_en: ["Peel and cube"], instructions_ro: ["Curăță și taie cuburi"], image_url: "https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?w=800", is_vegetarian: true, is_vegan: true },
  { id: 83, name: "Pineapple", name_ro: "Ananas", phase: 1, meal_type: "snack1", calories: 82, protein: 1, carbs: 22, fat: 0, ingredients_en: ["1 cup pineapple"], ingredients_ro: ["1 cană ananas"], instructions_en: ["Cut fresh pineapple"], instructions_ro: ["Taie ananas proaspăt"], image_url: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=800", is_vegetarian: true, is_vegan: true },
  { id: 84, name: "Plum", name_ro: "Prună", phase: 1, meal_type: "snack1", calories: 76, protein: 1, carbs: 19, fat: 0, ingredients_en: ["2 plums"], ingredients_ro: ["2 prune"], instructions_en: ["Wash and eat"], instructions_ro: ["Spală și mănâncă"], image_url: "https://images.unsplash.com/photo-1622032186476-62f0cf1f0231?w=800", is_vegetarian: true, is_vegan: true },
  { id: 85, name: "Nectarine", name_ro: "Nectarină", phase: 1, meal_type: "snack1", calories: 63, protein: 2, carbs: 15, fat: 0, ingredients_en: ["1 nectarine"], ingredients_ro: ["1 nectarină"], instructions_en: ["Wash and eat"], instructions_ro: ["Spală și mănâncă"], image_url: "https://images.unsplash.com/photo-1629828874514-944dd0d9c48b?w=800", is_vegetarian: true, is_vegan: true },
  { id: 86, name: "Cantaloupe", name_ro: "Pepene Galben", phase: 1, meal_type: "snack2", calories: 90, protein: 2, carbs: 22, fat: 0, ingredients_en: ["2 cups cantaloupe"], ingredients_ro: ["2 căni pepene galben"], instructions_en: ["Cube and serve"], instructions_ro: ["Taie cuburi și servește"], image_url: "https://images.unsplash.com/photo-1587049352846-4a222e784210?w=800", is_vegetarian: true, is_vegan: true },
  { id: 87, name: "Cherries", name_ro: "Cireșe", phase: 1, meal_type: "snack2", calories: 87, protein: 1, carbs: 22, fat: 0, ingredients_en: ["1 cup cherries"], ingredients_ro: ["1 cană cireșe"], instructions_en: ["Wash and pit"], instructions_ro: ["Spală și scoate sâmburii"], image_url: "https://images.unsplash.com/photo-1622207456002-1f44c043d7e5?w=800", is_vegetarian: true, is_vegan: true },
  { id: 88, name: "Apricots", name_ro: "Caise", phase: 1, meal_type: "snack2", calories: 79, protein: 2, carbs: 18, fat: 1, ingredients_en: ["3 apricots"], ingredients_ro: ["3 caise"], instructions_en: ["Wash and eat"], instructions_ro: ["Spală și mănâncă"], image_url: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=800", is_vegetarian: true, is_vegan: true },
  { id: 89, name: "Pomegranate Seeds", name_ro: "Boabe de Rodie", phase: 1, meal_type: "snack2", calories: 144, protein: 3, carbs: 32, fat: 2, ingredients_en: ["1 cup pomegranate seeds"], ingredients_ro: ["1 cană boabe rodie"], instructions_en: ["Extract seeds"], instructions_ro: ["Extrage boabele"], image_url: "https://images.unsplash.com/photo-1587656768072-fc5a31b5f0d6?w=800", is_vegetarian: true, is_vegan: true },
  { id: 90, name: "Grapefruit", name_ro: "Grepfrut", phase: 1, meal_type: "snack2", calories: 52, protein: 1, carbs: 13, fat: 0, ingredients_en: ["1/2 grapefruit"], ingredients_ro: ["1/2 grepfrut"], instructions_en: ["Peel and eat"], instructions_ro: ["Curăță și mănâncă"], image_url: "https://images.unsplash.com/photo-1556910128-54790ca2c723?w=800", is_vegetarian: true, is_vegan: true },

  // =============== PHASE 2 - REȚETE NOI ORIGINALE ===============
  // BREAKFAST (10 rețete noi)
  { id: 91, name: "Turkey Spinach Scramble", name_ro: "Omletă de Curcan cu Spanac", phase: 2, meal_type: "breakfast", calories: 210, protein: 32, carbs: 8, fat: 6, ingredients_en: ["150g ground turkey", "1 cup spinach", "3 egg whites"], ingredients_ro: ["150g curcan tocat", "1 cană spanac", "3 albușuri"], instructions_en: ["Cook turkey", "Add spinach and egg whites", "Scramble"], instructions_ro: ["Gătește curcan", "Adaugă spanac și albușuri", "Amestecă"], image_url: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800", is_vegetarian: false },
  { id: 92, name: "Chicken Vegetable Frittata", name_ro: "Frittata de Pui cu Legume", phase: 2, meal_type: "breakfast", calories: 195, protein: 30, carbs: 7, fat: 5, ingredients_en: ["120g chicken breast", "4 egg whites", "bell pepper", "onion"], ingredients_ro: ["120g piept pui", "4 albușuri", "ardei gras", "ceapă"], instructions_en: ["Dice chicken and vegetables", "Mix with egg whites", "Bake"], instructions_ro: ["Taie pui și legume", "Amestecă cu albușuri", "Coace"], image_url: "https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?w=800", is_vegetarian: false },
  { id: 93, name: "White Fish with Asparagus", name_ro: "Pește Alb cu Sparanghel", phase: 2, meal_type: "breakfast", calories: 185, protein: 28, carbs: 6, fat: 5, ingredients_en: ["150g white fish", "1 cup asparagus", "lemon"], ingredients_ro: ["150g pește alb", "1 cană sparanghel", "lămâie"], instructions_en: ["Steam fish", "Grill asparagus", "Season with lemon"], instructions_ro: ["Gătește pește la abur", "Gătește sparanghel", "Condimentează cu lămâie"], image_url: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800", is_vegetarian: false },
  { id: 94, name: "Turkey Zucchini Boats", name_ro: "Bărci de Dovlecel cu Curcan", phase: 2, meal_type: "breakfast", calories: 200, protein: 31, carbs: 9, fat: 5, ingredients_en: ["150g ground turkey", "2 zucchinis", "tomatoes", "herbs"], ingredients_ro: ["150g curcan tocat", "2 dovlecei", "roșii", "ierburi"], instructions_en: ["Hollow zucchinis", "Fill with cooked turkey", "Bake"], instructions_ro: ["Scobitește dovlecei", "Umple cu curcan gătit", "Coace"], image_url: "https://images.unsplash.com/photo-1628773822503-930a7eaecf80?w=800", is_vegetarian: false },
  { id: 95, name: "Egg White Mushroom Omelette", name_ro: "Omletă de Albuș cu Ciuperci", phase: 2, meal_type: "breakfast", calories: 170, protein: 26, carbs: 8, fat: 4, ingredients_en: ["5 egg whites", "1 cup mushrooms", "spinach"], ingredients_ro: ["5 albușuri", "1 cană ciuperci", "spanac"], instructions_en: ["Sauté mushrooms", "Add egg whites", "Fold omelette"], instructions_ro: ["Sotează ciuperci", "Adaugă albușuri", "Împăturește omleta"], image_url: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800", is_vegetarian: true },
  { id: 96, name: "Chicken Kale Sauté", name_ro: "Pui cu Kale Sotat", phase: 2, meal_type: "breakfast", calories: 190, protein: 29, carbs: 7, fat: 5, ingredients_en: ["150g chicken breast", "2 cups kale", "garlic"], ingredients_ro: ["150g piept pui", "2 căni kale", "usturoi"], instructions_en: ["Grill chicken", "Sauté kale with garlic"], instructions_ro: ["Gătește pui", "Sotează kale cu usturoi"], image_url: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800", is_vegetarian: false },
  { id: 97, name: "Turkey Bell Pepper Rings", name_ro: "Inele de Ardei cu Curcan", phase: 2, meal_type: "breakfast", calories: 205, protein: 32, carbs: 10, fat: 5, ingredients_en: ["150g turkey breast", "2 bell peppers", "egg whites"], ingredients_ro: ["150g piept curcan", "2 ardei grași", "albușuri"], instructions_en: ["Cut pepper rings", "Fill with turkey and egg whites", "Bake"], instructions_ro: ["Taie inele ardei", "Umple cu curcan și albușuri", "Coace"], image_url: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=800", is_vegetarian: false },
  { id: 98, name: "White Fish Tomato Stew", name_ro: "Tocană de Pește cu Roșii", phase: 2, meal_type: "breakfast", calories: 180, protein: 27, carbs: 9, fat: 4, ingredients_en: ["150g white fish", "2 tomatoes", "celery", "onion"], ingredients_ro: ["150g pește alb", "2 roșii", "țelină", "ceapă"], instructions_en: ["Simmer fish with vegetables"], instructions_ro: ["Fierbe pește cu legume"], image_url: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800", is_vegetarian: false },
  { id: 99, name: "Chicken Cabbage Rolls", name_ro: "Sarmale de Pui cu Varză", phase: 2, meal_type: "breakfast", calories: 195, protein: 30, carbs: 8, fat: 5, ingredients_en: ["150g ground chicken", "cabbage leaves", "tomatoes"], ingredients_ro: ["150g pui tocat", "frunze varză", "roșii"], instructions_en: ["Wrap chicken in cabbage", "Bake in tomato sauce"], instructions_ro: ["Înfășoară pui în varză", "Coace în sos roșii"], image_url: "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800", is_vegetarian: false },
  { id: 100, name: "Turkey Eggplant Stack", name_ro: "Stivă de Vânătă cu Curcan", phase: 2, meal_type: "breakfast", calories: 200, protein: 31, carbs: 10, fat: 6, ingredients_en: ["150g turkey breast", "1 eggplant", "tomatoes", "basil"], ingredients_ro: ["150g piept curcan", "1 vânătă", "roșii", "busuioc"], instructions_en: ["Grill eggplant slices", "Layer with turkey and tomatoes"], instructions_ro: ["Gătește felii vânătă", "Așează în straturi cu curcan și roșii"], image_url: "https://images.unsplash.com/photo-1628773822503-930a7eaecf80?w=800", is_vegetarian: false },

  // LUNCH (10 rețete noi)
  { id: 101, name: "Grilled Turkey Salad", name_ro: "Salată cu Curcan la Grătar", phase: 2, meal_type: "lunch", calories: 315, protein: 46, carbs: 10, fat: 10, ingredients_en: ["200g turkey breast", "mixed greens", "cucumber", "radishes"], ingredients_ro: ["200g piept curcan", "salată mixtă", "castravete", "ridichi"], instructions_en: ["Grill turkey", "Toss with fresh vegetables"], instructions_ro: ["Gătește curcan", "Amestecă cu legume proaspete"], image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800", is_vegetarian: false },
  { id: 102, name: "Chicken Broccoli Bowl", name_ro: "Bowl de Pui cu Broccoli", phase: 2, meal_type: "lunch", calories: 305, protein: 44, carbs: 12, fat: 9, ingredients_en: ["200g chicken breast", "2 cups broccoli", "lemon juice"], ingredients_ro: ["200g piept pui", "2 căni broccoli", "suc lămâie"], instructions_en: ["Steam broccoli", "Grill chicken", "Combine"], instructions_ro: ["Gătește broccoli la abur", "Gătește pui", "Combină"], image_url: "https://images.unsplash.com/photo-1628773822503-930a7eaecf80?w=800", is_vegetarian: false },
  { id: 103, name: "Salmon Spinach Salad", name_ro: "Salată de Somon cu Spanac", phase: 2, meal_type: "lunch", calories: 330, protein: 42, carbs: 8, fat: 14, ingredients_en: ["180g salmon", "2 cups spinach", "cherry tomatoes", "lemon"], ingredients_ro: ["180g somon", "2 căni spanac", "roșii cherry", "lămâie"], instructions_en: ["Grill salmon", "Serve on fresh spinach"], instructions_ro: ["Gătește somon", "Servește pe spanac proaspăt"], image_url: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800", is_vegetarian: false },
  { id: 104, name: "Turkey Cauliflower Mash", name_ro: "Curcan cu Piure de Conopidă", phase: 2, meal_type: "lunch", calories: 295, protein: 45, carbs: 14, fat: 8, ingredients_en: ["200g turkey breast", "2 cups cauliflower", "garlic"], ingredients_ro: ["200g piept curcan", "2 căni conopidă", "usturoi"], instructions_en: ["Mash steamed cauliflower", "Serve with grilled turkey"], instructions_ro: ["Piureză conopidă la abur", "Servește cu curcan la grătar"], image_url: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800", is_vegetarian: false },
  { id: 105, name: "White Fish Vegetable Soup", name_ro: "Supă de Pește cu Legume", phase: 2, meal_type: "lunch", calories: 280, protein: 40, carbs: 12, fat: 8, ingredients_en: ["200g white fish", "celery", "carrots", "onion", "zucchini"], ingredients_ro: ["200g pește alb", "țelină", "morcovi", "ceapă", "dovlecel"], instructions_en: ["Boil vegetables", "Add fish chunks", "Simmer"], instructions_ro: ["Fierbe legume", "Adaugă bucăți pește", "Las la fiert"], image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800", is_vegetarian: false },
  { id: 106, name: "Chicken Lettuce Boats", name_ro: "Bărci de Salată cu Pui", phase: 2, meal_type: "lunch", calories: 300, protein: 43, carbs: 8, fat: 11, ingredients_en: ["200g chicken breast", "lettuce leaves", "bell pepper", "cucumber"], ingredients_ro: ["200g piept pui", "frunze salată", "ardei gras", "castravete"], instructions_en: ["Dice chicken and vegetables", "Serve in lettuce cups"], instructions_ro: ["Taie pui și legume cubulețe", "Servește în căușe de salată"], image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800", is_vegetarian: false },
  { id: 107, name: "Turkey Stuffed Tomatoes", name_ro: "Roșii Umplute cu Curcan", phase: 2, meal_type: "lunch", calories: 310, protein: 44, carbs: 14, fat: 9, ingredients_en: ["200g ground turkey", "4 large tomatoes", "herbs", "onion"], ingredients_ro: ["200g curcan tocat", "4 roșii mari", "ierburi", "ceapă"], instructions_en: ["Hollow tomatoes", "Fill with cooked turkey", "Bake"], instructions_ro: ["Scobitește roșii", "Umple cu curcan gătit", "Coace"], image_url: "https://images.unsplash.com/photo-1592838064575-70ed626d3a0e?w=800", is_vegetarian: false },
  { id: 108, name: "Grilled Chicken with Bok Choy", name_ro: "Pui la Grătar cu Bok Choy", phase: 2, meal_type: "lunch", calories: 295, protein: 45, carbs: 10, fat: 9, ingredients_en: ["200g chicken breast", "2 cups bok choy", "ginger", "garlic"], ingredients_ro: ["200g piept pui", "2 căni bok choy", "ghimbir", "usturoi"], instructions_en: ["Grill chicken", "Stir-fry bok choy"], instructions_ro: ["Gătește pui", "Sotează bok choy"], image_url: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800", is_vegetarian: false },
  { id: 109, name: "Turkey Mushroom Stew", name_ro: "Tocană de Curcan cu Ciuperci", phase: 2, meal_type: "lunch", calories: 320, protein: 46, carbs: 12, fat: 10, ingredients_en: ["200g turkey breast", "2 cups mushrooms", "onion", "celery"], ingredients_ro: ["200g piept curcan", "2 căni ciuperci", "ceapă", "țelină"], instructions_en: ["Dice turkey and vegetables", "Simmer 25 min"], instructions_ro: ["Taie curcan și legume", "Las la fiert 25 min"], image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800", is_vegetarian: false },
  { id: 110, name: "White Fish Brussels Sprouts", name_ro: "Pește cu Varză de Bruxelles", phase: 2, meal_type: "lunch", calories: 285, protein: 41, carbs: 16, fat: 8, ingredients_en: ["200g white fish", "2 cups brussels sprouts", "lemon"], ingredients_ro: ["200g pește alb", "2 căni varză Bruxelles", "lămâie"], instructions_en: ["Roast brussels sprouts", "Bake fish", "Serve together"], instructions_ro: ["Coace varză", "Coace pește", "Servește împreună"], image_url: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800", is_vegetarian: false },

  // DINNER (10 rețete noi) + SNACKS (10 rețete noi) Phase 2
  { id: 111, name: "Grilled Chicken Zucchini", name_ro: "Pui cu Dovlecel", phase: 2, meal_type: "dinner", calories: 340, protein: 50, carbs: 12, fat: 12, ingredients_en: ["220g chicken", "2 zucchinis", "tomatoes"], ingredients_ro: ["220g pui", "2 dovlecei", "roșii"], instructions_en: ["Grill", "Serve"], instructions_ro: ["Gătește", "Servește"], image_url: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800", is_vegetarian: false },
  { id: 112, name: "Turkey Spinach Bake", name_ro: "Curcan cu Spanac", phase: 2, meal_type: "dinner", calories: 335, protein: 48, carbs: 10, fat: 13, ingredients_en: ["220g turkey", "spinach", "egg whites"], ingredients_ro: ["220g curcan", "spanac", "albușuri"], instructions_en: ["Bake"], instructions_ro: ["Coace"], image_url: "https://images.unsplash.com/photo-1628773822503-930a7eaecf80?w=800", is_vegetarian: false },
  { id: 113, name: "Salmon Asparagus", name_ro: "Somon cu Sparanghel", phase: 2, meal_type: "dinner", calories: 360, protein: 46, carbs: 8, fat: 16, ingredients_en: ["200g salmon", "asparagus"], ingredients_ro: ["200g somon", "sparanghel"], instructions_en: ["Grill"], instructions_ro: ["Gătește"], image_url: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800", is_vegetarian: false },
  { id: 114, name: "Chicken Cabbage Stir-Fry", name_ro: "Pui cu Varză", phase: 2, meal_type: "dinner", calories: 325, protein: 48, carbs: 14, fat: 11, ingredients_en: ["220g chicken", "cabbage"], ingredients_ro: ["220g pui", "varză"], instructions_en: ["Stir-fry"], instructions_ro: ["Sotează"], image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800", is_vegetarian: false },
  { id: 115, name: "Turkey Pepper Skillet", name_ro: "Curcan cu Ardei", phase: 2, meal_type: "dinner", calories: 330, protein: 49, carbs: 12, fat: 12, ingredients_en: ["220g turkey", "bell peppers"], ingredients_ro: ["220g curcan", "ardei"], instructions_en: ["Cook"], instructions_ro: ["Gătește"], image_url: "https://images.unsplash.com/photo-1628773822503-930a7eaecf80?w=800", is_vegetarian: false },
  { id: 116, name: "White Fish Celery", name_ro: "Pește cu Țelină", phase: 2, meal_type: "dinner", calories: 310, protein: 45, carbs: 10, fat: 11, ingredients_en: ["220g fish", "celery"], ingredients_ro: ["220g pește", "țelină"], instructions_en: ["Bake"], instructions_ro: ["Coace"], image_url: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800", is_vegetarian: false },
  { id: 117, name: "Chicken Tomato Herbs", name_ro: "Pui cu Roșii", phase: 2, meal_type: "dinner", calories: 320, protein: 47, carbs: 11, fat: 12, ingredients_en: ["220g chicken", "tomatoes", "basil"], ingredients_ro: ["220g pui", "roșii", "busuioc"], instructions_en: ["Bake"], instructions_ro: ["Coace"], image_url: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800", is_vegetarian: false },
  { id: 118, name: "Turkey Eggplant", name_ro: "Curcan cu Vânătă", phase: 2, meal_type: "dinner", calories: 335, protein: 48, carbs: 13, fat: 12, ingredients_en: ["220g turkey", "eggplant"], ingredients_ro: ["220g curcan", "vânătă"], instructions_en: ["Grill"], instructions_ro: ["Gătește"], image_url: "https://images.unsplash.com/photo-1628773822503-930a7eaecf80?w=800", is_vegetarian: false },
  { id: 119, name: "Salmon Kale", name_ro: "Somon cu Kale", phase: 2, meal_type: "dinner", calories: 355, protein: 46, carbs: 9, fat: 16, ingredients_en: ["200g salmon", "kale"], ingredients_ro: ["200g somon", "kale"], instructions_en: ["Bake"], instructions_ro: ["Coace"], image_url: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800", is_vegetarian: false },
  { id: 120, name: "Chicken Green Beans", name_ro: "Pui cu Fasole Verde", phase: 2, meal_type: "dinner", calories: 315, protein: 48, carbs: 10, fat: 11, ingredients_en: ["220g chicken", "green beans"], ingredients_ro: ["220g pui", "fasole verde"], instructions_en: ["Grill"], instructions_ro: ["Gătește"], image_url: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800", is_vegetarian: false },
  { id: 121, name: "Egg White Bites", name_ro: "Buc ăți Albuș", phase: 2, meal_type: "snack1", calories: 95, protein: 20, carbs: 2, fat: 1, ingredients_en: ["4 egg whites"], ingredients_ro: ["4 albușuri"], instructions_en: ["Bake"], instructions_ro: ["Coace"], image_url: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800", is_vegetarian: true },
  { id: 122, name: "Turkey Jerky", name_ro: "Jerky Curcan", phase: 2, meal_type: "snack1", calories: 110, protein: 22, carbs: 3, fat: 2, ingredients_en: ["turkey jerky"], ingredients_ro: ["jerky curcan"], instructions_en: ["Portion"], instructions_ro: ["Porționează"], image_url: "https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=800", is_vegetarian: false },
  { id: 123, name: "Chicken Strips", name_ro: "Fâșii Pui", phase: 2, meal_type: "snack1", calories: 100, protein: 21, carbs: 2, fat: 2, ingredients_en: ["chicken breast"], ingredients_ro: ["piept pui"], instructions_en: ["Grill"], instructions_ro: ["Gătește"], image_url: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800", is_vegetarian: false },
  { id: 124, name: "Radishes", name_ro: "Ridichi", phase: 2, meal_type: "snack1", calories: 35, protein: 1, carbs: 8, fat: 0, ingredients_en: ["radishes"], ingredients_ro: ["ridichi"], instructions_en: ["Wash"], instructions_ro: ["Spală"], image_url: "https://images.unsplash.com/photo-1604977042946-1eecc30f269e?w=800", is_vegetarian: true, is_vegan: true },
  { id: 125, name: "Celery Sticks", name_ro: "Băt oane Țelină", phase: 2, meal_type: "snack1", calories: 15, protein: 1, carbs: 3, fat: 0, ingredients_en: ["celery"], ingredients_ro: ["țelină"], instructions_en: ["Cut"], instructions_ro: ["Taie"], image_url: "https://images.unsplash.com/photo-1529288475508-c303ace43d0f?w=800", is_vegetarian: true, is_vegan: true },
  { id: 126, name: "Egg Whites", name_ro: "Albușuri", phase: 2, meal_type: "snack2", calories: 85, protein: 18, carbs: 1, fat: 0, ingredients_en: ["5 egg whites"], ingredients_ro: ["5 albușuri"], instructions_en: ["Boil"], instructions_ro: ["Fierbe"], image_url: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800", is_vegetarian: true },
  { id: 127, name: "Turkey Breast", name_ro: "Piept Curcan", phase: 2, meal_type: "snack2", calories: 100, protein: 20, carbs: 2, fat: 2, ingredients_en: ["turkey"], ingredients_ro: ["curcan"], instructions_en: ["Slice"], instructions_ro: ["Taie"], image_url: "https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=800", is_vegetarian: false },
  { id: 128, name: "Broccoli Florets", name_ro: "Buchetedde Broccoli", phase: 2, meal_type: "snack2", calories: 55, protein: 4, carbs: 11, fat: 1, ingredients_en: ["broccoli"], ingredients_ro: ["broccoli"], instructions_en: ["Steam"], instructions_ro: ["La abur"], image_url: "https://images.unsplash.com/photo-1628773822503-930a7eaecf80?w=800", is_vegetarian: true, is_vegan: true },
  { id: 129, name: "Spinach Leaves", name_ro: "Frunze Spanac", phase: 2, meal_type: "snack2", calories: 25, protein: 3, carbs: 4, fat: 0, ingredients_en: ["spinach"], ingredients_ro: ["spanac"], instructions_en: ["Wash"], instructions_ro: ["Spală"], image_url: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=800", is_vegetarian: true, is_vegan: true },
  { id: 130, name: "Cauliflower Bites", name_ro: "Bucăți Conopidă", phase: 2, meal_type: "snack2", calories: 50, protein: 4, carbs: 10, fat: 1, ingredients_en: ["cauliflower"], ingredients_ro: ["conopidă"], instructions_en: ["Roast"], instructions_ro: ["Coace"], image_url: "https://images.unsplash.com/photo-1568584711271-35691ece32df?w=800", is_vegetarian: true, is_vegan: true },

  // =============== PHASE 3 - REȚETE NOI ORIGINALE ===============
  // BREAKFAST (10) + LUNCH (10) + DINNER (10) + SNACKS (10)
  { id: 131, name: "Avocado Egg Toast", name_ro: "Toast Avocado Ou", phase: 3, meal_type: "breakfast", calories: 410, protein: 22, carbs: 32, fat: 24, ingredients_en: ["rye bread", "avocado", "eggs"], ingredients_ro: ["pâine secară", "avocado", "ouă"], instructions_en: ["Toast", "Top"], instructions_ro: ["Prăjește", "Adaugă"], image_url: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800", is_vegetarian: true },
  { id: 132, name: "Salmon Quinoa Bowl", name_ro: "Bowl Somon Quinoa", phase: 3, meal_type: "breakfast", calories: 450, protein: 35, carbs: 38, fat: 22, ingredients_en: ["salmon", "quinoa", "avocado"], ingredients_ro: ["somon", "quinoa", "avocado"], instructions_en: ["Cook", "Mix"], instructions_ro: ["Gătește", "Amestecă"], image_url: "https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?w=800", is_vegetarian: false },
  { id: 133, name: "Nut Butter Oats", name_ro: "Ovăz cu Unt Arahide", phase: 3, meal_type: "breakfast", calories: 390, protein: 18, carbs: 42, fat: 20, ingredients_en: ["oats", "almond butter", "berries"], ingredients_ro: ["ovăz", "unt migdale", "fructe"], instructions_en: ["Cook", "Top"], instructions_ro: ["Fierbe", "Adaugă"], image_url: "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800", is_vegetarian: true },
  { id: 134, name: "Turkey Avocado Wrap", name_ro: "Wrap Curcan Avocado", phase: 3, meal_type: "breakfast", calories: 420, protein: 32, carbs: 35, fat: 22, ingredients_en: ["turkey", "avocado", "wrap"], ingredients_ro: ["curcan", "avocado", "wrap"], instructions_en: ["Wrap"], instructions_ro: ["Înfășoară"], image_url: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800", is_vegetarian: false },
  { id: 135, name: "Chicken Omelette", name_ro: "Omletă Pui", phase: 3, meal_type: "breakfast", calories: 380, protein: 36, carbs: 12, fat: 24, ingredients_en: ["eggs", "chicken", "cheese"], ingredients_ro: ["ouă", "pui", "brânză"], instructions_en: ["Cook"], instructions_ro: ["Gătește"], image_url: "https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?w=800", is_vegetarian: false },
  { id: 136, name: "Smoothie Bowl", name_ro: "Bol Smoothie", phase: 3, meal_type: "breakfast", calories: 360, protein: 18, carbs: 48, fat: 16, ingredients_en: ["berries", "nuts", "protein"], ingredients_ro: ["fructe", "nuci", "proteină"], instructions_en: ["Blend", "Top"], instructions_ro: ["Mixează", "Adaugă"], image_url: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800", is_vegetarian: true },
  { id: 137, name: "Egg Muffins", name_ro: "Briose Ouă", phase: 3, meal_type: "breakfast", calories: 340, protein: 24, carbs: 22, fat: 20, ingredients_en: ["eggs", "vegetables", "cheese"], ingredients_ro: ["ouă", "legume", "brânză"], instructions_en: ["Bake"], instructions_ro: ["Coace"], image_url: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800", is_vegetarian: true },
  { id: 138, name: "Greek Yogurt Nuts", name_ro: "Iaurt Grec Nuci", phase: 3, meal_type: "breakfast", calories: 320, protein: 22, carbs: 28, fat: 18, ingredients_en: ["greek yogurt", "walnuts", "honey"], ingredients_ro: ["iaurt grec", "nuci", "miere"], instructions_en: ["Mix"], instructions_ro: ["Amestecă"], image_url: "https://images.unsplash.com/photo-1488477304112-4944851de03d?w=800", is_vegetarian: true },
  { id: 139, name: "Protein Pancakes", name_ro: "Clătite Proteice", phase: 3, meal_type: "breakfast", calories: 370, protein: 28, carbs: 36, fat: 16, ingredients_en: ["protein powder", "eggs", "oats"], ingredients_ro: ["proteină", "ouă", "ovăz"], instructions_en: ["Cook"], instructions_ro: ["Gătește"], image_url: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=800", is_vegetarian: true },
  { id: 140, name: "Chia Pudding", name_ro: "Budincă Chia", phase: 3, meal_type: "breakfast", calories: 310, protein: 16, carbs: 32, fat: 18, ingredients_en: ["chia seeds", "almond milk", "berries"], ingredients_ro: ["semințe chia", "lapte migdale", "fructe"], instructions_en: ["Soak", "Top"], instructions_ro: ["Înmoaie", "Adaugă"], image_url: "https://images.unsplash.com/photo-1502741126161-b048400d085d?w=800", is_vegetarian: true },
  { id: 141, name: "Salmon Avocado Salad", name_ro: "Salată Somon Avocado", phase: 3, meal_type: "lunch", calories: 480, protein: 40, carbs: 26, fat: 28, ingredients_en: ["salmon", "avocado", "greens"], ingredients_ro: ["somon", "avocado", "salată"], instructions_en: ["Grill", "Toss"], instructions_ro: ["Gătește", "Amestecă"], image_url: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800", is_vegetarian: false },
  { id: 142, name: "Chicken Quinoa", name_ro: "Pui cu Quinoa", phase: 3, meal_type: "lunch", calories: 460, protein: 42, carbs: 38, fat: 20, ingredients_en: ["chicken", "quinoa", "olive oil"], ingredients_ro: ["pui", "quinoa", "ulei măsline"], instructions_en: ["Cook"], instructions_ro: ["Gătește"], image_url: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800", is_vegetarian: false },
  { id: 143, name: "Turkey Rice Bowl", name_ro: "Bol Curcan Orez", phase: 3, meal_type: "lunch", calories: 470, protein: 40, carbs: 45, fat: 18, ingredients_en: ["turkey", "brown rice", "vegetables"], ingredients_ro: ["curcan", "orez brun", "legume"], instructions_en: ["Mix"], instructions_ro: ["Amestecă"], image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800", is_vegetarian: false },
  { id: 144, name: "Tuna Sweet Potato", name_ro: "Ton Cartof Dulce", phase: 3, meal_type: "lunch", calories: 450, protein: 38, carbs: 42, fat: 16, ingredients_en: ["tuna", "sweet potato", "greens"], ingredients_ro: ["ton", "cartof dulce", "salată"], instructions_en: ["Bake"], instructions_ro: ["Coace"], image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800", is_vegetarian: false },
  { id: 145, name: "Chicken Pasta", name_ro: "Paste cu Pui", phase: 3, meal_type: "lunch", calories: 490, protein: 40, carbs: 48, fat: 20, ingredients_en: ["chicken", "whole wheat pasta", "pesto"], ingredients_ro: ["pui", "paste integrale", "pesto"], instructions_en: ["Cook"], instructions_ro: ["Gătește"], image_url: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800", is_vegetarian: false },
  { id: 146, name: "Fish Tacos", name_ro: "Tacos cu Pește", phase: 3, meal_type: "lunch", calories: 440, protein: 36, carbs: 40, fat: 18, ingredients_en: ["fish", "corn tortillas", "avocado"], ingredients_ro: ["pește", "tortillas", "avocado"], instructions_en: ["Assemble"], instructions_ro: ["Asamblează"], image_url: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800", is_vegetarian: false },
  { id: 147, name: "Turkey Burrito", name_ro: "Burrito Curcan", phase: 3, meal_type: "lunch", calories: 510, protein: 42, carbs: 50, fat: 22, ingredients_en: ["turkey", "beans", "avocado", "wrap"], ingredients_ro: ["curcan", "fasole", "avocado", "wrap"], instructions_en: ["Wrap"], instructions_ro: ["Înfășoară"], image_url: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800", is_vegetarian: false },
  { id: 148, name: "Salmon Poke Bowl", name_ro: "Poke Bowl Somon", phase: 3, meal_type: "lunch", calories: 500, protein: 38, carbs: 44, fat: 24, ingredients_en: ["salmon", "rice", "avocado", "sesame"], ingredients_ro: ["somon", "orez", "avocado", "susan"], instructions_en: ["Mix"], instructions_ro: ["Amestecă"], image_url: "https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?w=800", is_vegetarian: false },
  { id: 149, name: "Chicken Veggie Wrap", name_ro: "Wrap Pui Legume", phase: 3, meal_type: "lunch", calories: 430, protein: 38, carbs: 36, fat: 18, ingredients_en: ["chicken", "hummus", "vegetables", "wrap"], ingredients_ro: ["pui", "hummus", "legume", "wrap"], instructions_en: ["Wrap"], instructions_ro: ["Înfășoară"], image_url: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800", is_vegetarian: false },
  { id: 150, name: "Egg Salad Sandwich", name_ro: "Sandviș Salată Ouă", phase: 3, meal_type: "lunch", calories: 410, protein: 24, carbs: 38, fat: 20, ingredients_en: ["eggs", "rye bread", "avocado"], ingredients_ro: ["ouă", "pâine secară", "avocado"], instructions_en: ["Mix", "Assemble"], instructions_ro: ["Amestecă", "Asamblează"], image_url: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800", is_vegetarian: true },
  { id: 151, name: "Beef Stir-Fry", name_ro: "Vită Sotată", phase: 3, meal_type: "dinner", calories: 550, protein: 48, carbs: 42, fat: 24, ingredients_en: ["beef", "vegetables", "cashews"], ingredients_ro: ["vită", "legume", "caju"], instructions_en: ["Stir-fry"], instructions_ro: ["Sotează"], image_url: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800", is_vegetarian: false },
  { id: 152, name: "Salmon Pasta", name_ro: "Paste cu Somon", phase: 3, meal_type: "dinner", calories: 540, protein: 42, carbs: 48, fat: 26, ingredients_en: ["salmon", "pasta", "cream"], ingredients_ro: ["somon", "paste", "smântână"], instructions_en: ["Cook"], instructions_ro: ["Gătește"], image_url: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800", is_vegetarian: false },
  { id: 153, name: "Chicken Curry", name_ro: "Curry Pui", phase: 3, meal_type: "dinner", calories: 520, protein: 44, carbs: 46, fat: 22, ingredients_en: ["chicken", "coconut milk", "rice"], ingredients_ro: ["pui", "lapte cocos", "orez"], instructions_en: ["Simmer"], instructions_ro: ["Fierbe"], image_url: "https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?w=800", is_vegetarian: false },
  { id: 154, name: "Turkey Meatballs", name_ro: "Chiftele Curcan", phase: 3, meal_type: "dinner", calories: 480, protein: 42, carbs: 36, fat: 24, ingredients_en: ["turkey", "pasta", "tomato sauce"], ingredients_ro: ["curcan", "paste", "sos roșii"], instructions_en: ["Bake"], instructions_ro: ["Coace"], image_url: "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800", is_vegetarian: false },
  { id: 155, name: "Pork Tenderloin", name_ro: "Muschi Porc", phase: 3, meal_type: "dinner", calories: 510, protein: 46, carbs: 38, fat: 24, ingredients_en: ["pork", "sweet potato", "asparagus"], ingredients_ro: ["porc", "cartof dulce", "sparanghel"], instructions_en: ["Roast"], instructions_ro: ["Coace"], image_url: "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=800", is_vegetarian: false },
  { id: 156, name: "Lamb Quinoa", name_ro: "Miel cu Quinoa", phase: 3, meal_type: "dinner", calories: 560, protein: 44, carbs: 40, fat: 28, ingredients_en: ["lamb", "quinoa", "vegetables"], ingredients_ro: ["miel", "quinoa", "legume"], instructions_en: ["Grill"], instructions_ro: ["Gătește"], image_url: "https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=800", is_vegetarian: false },
  { id: 157, name: "Shrimp Risotto", name_ro: "Risotto cu Creveți", phase: 3, meal_type: "dinner", calories: 490, protein: 36, carbs: 52, fat: 20, ingredients_en: ["shrimp", "arborio rice", "parmesan"], ingredients_ro: ["creveți", "orez arborio", "parmezan"], instructions_en: ["Cook"], instructions_ro: ["Gătește"], image_url: "https://images.unsplash.com/photo-1633504581786-316c8002b1b9?w=800", is_vegetarian: false },
  { id: 158, name: "Duck Breast", name_ro: "Piept Rață", phase: 3, meal_type: "dinner", calories: 580, protein: 46, carbs: 34, fat: 32, ingredients_en: ["duck", "wild rice", "orange"], ingredients_ro: ["rață", "orez sălbatic", "portocală"], instructions_en: ["Sear"], instructions_ro: ["Prăjește"], image_url: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800", is_vegetarian: false },
  { id: 159, name: "Cod Mediterranean", name_ro: "Cod Mediteranean", phase: 3, meal_type: "dinner", calories: 460, protein: 42, carbs: 38, fat: 20, ingredients_en: ["cod", "olives", "tomatoes", "couscous"], ingredients_ro: ["cod", "măsline", "roșii", "cuscus"], instructions_en: ["Bake"], instructions_ro: ["Coace"], image_url: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800", is_vegetarian: false },
  { id: 160, name: "Chicken Thighs Roasted", name_ro: "Pulpe Pui Coapte", phase: 3, meal_type: "dinner", calories: 530, protein: 44, carbs: 36, fat: 28, ingredients_en: ["chicken thighs", "potatoes", "herbs"], ingredients_ro: ["pulpe pui", "cartofi", "ierburi"], instructions_en: ["Roast"], instructions_ro: ["Coace"], image_url: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800", is_vegetarian: false },
  { id: 161, name: "Trail Mix", name_ro: "Mix Nuci", phase: 3, meal_type: "snack1", calories: 210, protein: 6, carbs: 18, fat: 16, ingredients_en: ["almonds", "cashews", "raisins"], ingredients_ro: ["migdale", "caju", "stafide"], instructions_en: ["Mix"], instructions_ro: ["Amestecă"], image_url: "https://images.unsplash.com/photo-1569288063643-5d29ad64df09?w=800", is_vegetarian: true },
  { id: 162, name: "Avocado Toast", name_ro: "Toast cu Avocado", phase: 3, meal_type: "snack1", calories: 220, protein: 6, carbs: 20, fat: 15, ingredients_en: ["avocado", "whole grain bread", "olive oil"], ingredients_ro: ["avocado", "pâine integrală", "ulei măsline"], instructions_en: ["Mash and spread"], instructions_ro: ["Pisează și întinde"], image_url: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800", is_vegetarian: true },
  { id: 163, name: "Peanut Butter Apple", name_ro: "Măr Unt Arahide", phase: 3, meal_type: "snack1", calories: 230, protein: 7, carbs: 26, fat: 14, ingredients_en: ["apple", "peanut butter"], ingredients_ro: ["măr", "unt arahide"], instructions_en: ["Spread"], instructions_ro: ["Întinde"], image_url: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=800", is_vegetarian: true },
  { id: 164, name: "Greek Yogurt Berries", name_ro: "Iaurt Grec Fructe", phase: 3, meal_type: "snack1", calories: 180, protein: 12, carbs: 22, fat: 8, ingredients_en: ["greek yogurt", "berries"], ingredients_ro: ["iaurt grec", "fructe"], instructions_en: ["Mix"], instructions_ro: ["Amestecă"], image_url: "https://images.unsplash.com/photo-1488477304112-4944851de03d?w=800", is_vegetarian: true },
  { id: 165, name: "Energy Balls", name_ro: "Bilute Energizante", phase: 3, meal_type: "snack1", calories: 200, protein: 6, carbs: 24, fat: 12, ingredients_en: ["dates", "nuts", "coconut"], ingredients_ro: ["curmale", "nuci", "cocos"], instructions_en: ["Roll"], instructions_ro: ["Rulează"], image_url: "https://images.unsplash.com/photo-1564355808853-4dd0e4eaac6d?w=800", is_vegetarian: true, is_vegan: true },
  { id: 166, name: "Avocado Half", name_ro: "Jumătate Avocado", phase: 3, meal_type: "snack2", calories: 160, protein: 2, carbs: 9, fat: 15, ingredients_en: ["avocado"], ingredients_ro: ["avocado"], instructions_en: ["Slice"], instructions_ro: ["Taie"], image_url: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=800", is_vegetarian: true, is_vegan: true },
  { id: 167, name: "Mixed Nuts", name_ro: "Nuci Mixte", phase: 3, meal_type: "snack2", calories: 180, protein: 5, carbs: 8, fat: 16, ingredients_en: ["mixed nuts"], ingredients_ro: ["nuci mixte"], instructions_en: ["Portion"], instructions_ro: ["Porționează"], image_url: "https://images.unsplash.com/photo-1622484211043-e6d2f7d5a5eb?w=800", is_vegetarian: true, is_vegan: true },
  { id: 168, name: "Cheese Crackers", name_ro: "Brânză Crackers", phase: 3, meal_type: "snack2", calories: 170, protein: 8, carbs: 14, fat: 10, ingredients_en: ["cheese", "whole grain crackers"], ingredients_ro: ["brânză", "crackeri integrali"], instructions_en: ["Serve"], instructions_ro: ["Servește"], image_url: "https://images.unsplash.com/photo-1452195100486-9cc805987862?w=800", is_vegetarian: true },
  { id: 169, name: "Olives", name_ro: "Măsline", phase: 3, meal_type: "snack2", calories: 115, protein: 1, carbs: 6, fat: 11, ingredients_en: ["olives"], ingredients_ro: ["măsline"], instructions_en: ["Portion"], instructions_ro: ["Porționează"], image_url: "https://images.unsplash.com/photo-1452195100486-9cc805987862?w=800", is_vegetarian: true, is_vegan: true },
  { id: 170, name: "Sunflower Seeds", name_ro: "Semințe Floarea-Soarelui", phase: 3, meal_type: "snack2", calories: 165, protein: 6, carbs: 7, fat: 14, ingredients_en: ["sunflower seeds"], ingredients_ro: ["semințe floarea-soarelui"], instructions_en: ["Portion"], instructions_ro: ["Porționează"], image_url: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800", is_vegetarian: true, is_vegan: true }
];

export default async function handler(req, res) {
  // CORS
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }
  
  // Handle food ingredients request (Food Database)
  if (req.query.food === 'list' || req.query.food === 'search') {
    try {
      // Ensure food_ingredients table exists
      await pool.query(`
        CREATE TABLE IF NOT EXISTS food_ingredients (
          id SERIAL PRIMARY KEY,
          name_en VARCHAR(255) NOT NULL,
          name_ro VARCHAR(255) NOT NULL,
          category VARCHAR(100),
          calories_per_100g DECIMAL(6,2),
          protein_per_100g DECIMAL(6,2),
          carbs_per_100g DECIMAL(6,2),
          fat_per_100g DECIMAL(6,2),
          fiber_per_100g DECIMAL(6,2),
          is_approved BOOLEAN DEFAULT TRUE,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
      `);
      
      await pool.query(`CREATE INDEX IF NOT EXISTS idx_food_name_ro ON food_ingredients(name_ro)`);
      await pool.query(`CREATE INDEX IF NOT EXISTS idx_food_category ON food_ingredients(category)`);
      
      // Check if table is empty (seed needed)
      const countResult = await pool.query('SELECT COUNT(*) FROM food_ingredients');
      const count = parseInt(countResult.rows[0].count);
      
      if (count === 0) {
        console.log('📦 Seeding food database - run seed script manually or via migration');
        // Note: Seeding se face manual sau prin script separat
        // Pentru a evita timeout-uri la deployment
      }
      
      // Search or list
      if (req.query.food === 'search') {
        const { q } = req.query;
        const result = await pool.query(`
          SELECT * FROM food_ingredients
          WHERE name_ro ILIKE $1 OR name_en ILIKE $1
          ORDER BY name_ro
          LIMIT 50
        `, [`%${q}%`]);
        return res.status(200).json(result.rows);
      }
      
      // List all
      const result = await pool.query(`
        SELECT * FROM food_ingredients
        ORDER BY category, name_ro
        LIMIT 500
      `);
      return res.status(200).json(result.rows);
    } catch (error) {
      console.error('❌ Food database error:', error);
      return res.status(500).json({ error: error.message });
    }
  }
  
  // Handle countries request (combined to stay within Vercel 12 function limit)
  if (req.query.countries === 'true') {
    const countries = [
      { id: 1, name: 'România', code: 'RO', cities: ['București', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova', 'Brașov', 'Galați', 'Ploiești', 'Oradea'] },
      { id: 2, name: 'Moldova', code: 'MD', cities: ['Chișinău', 'Tiraspol', 'Bălți', 'Bender', 'Rîbnița'] },
      { id: 3, name: 'United States', code: 'US', cities: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'] },
      { id: 4, name: 'United Kingdom', code: 'GB', cities: ['London', 'Birmingham', 'Manchester', 'Leeds', 'Glasgow', 'Liverpool', 'Newcastle', 'Sheffield', 'Bristol', 'Edinburgh'] },
      { id: 5, name: 'Germany', code: 'DE', cities: ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig'] },
      { id: 6, name: 'France', code: 'FR', cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille'] },
      { id: 7, name: 'Italy', code: 'IT', cities: ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Bari', 'Catania'] },
      { id: 8, name: 'Spain', code: 'ES', cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Palma', 'Las Palmas', 'Bilbao'] },
      { id: 9, name: 'Canada', code: 'CA', cities: ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Kitchener'] },
      { id: 10, name: 'Australia', code: 'AU', cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Canberra', 'Newcastle', 'Wollongong', 'Logan City'] }
    ];
    return res.status(200).json(countries);
  }
  
  // Returnează rețetele HARDCODED
  return res.status(200).json(recipes);
}
